// ─── Standard ATR (Action Taken Report) data model ───
// Mirrors the comprehensive format in ATR_Comprehensive_Sample.pdf. Every field
// below the required core is optional so the renderer can omit anything missing.

export type AtrRisk = 'Critical' | 'High' | 'Medium' | 'Low' | 'Not Applicable';
export type AtrClassification =
  | 'Design Deficiency'
  | 'System Deficiency'
  | 'Procedural Non-Compliance'
  | 'Other';

/** The Risk Owner's first call on an observation: is it real? */
export type AtrVerdict = 'True Exception' | 'False Positive';
/** Where an action plan sits in the auditor's approval of the plan itself. */
export type AtrPlanReview = 'Pending' | 'Approved' | 'Rejected';
export type AtrObservationStatus = 'Closed' | 'In Progress' | 'Open' | 'Overdue';
export type AtrActionStatus =
  | 'Implemented'
  | 'Partially Implemented'
  | 'Pending'
  | 'Overdue'
  | 'Not Due';

export interface AtrActionPlan {
  /** Short title for the management action plan. */
  title?: string;
  /** Recommendation / management action plan text. */
  text: string;
  dueDate?: string;                 // ISO or free text (e.g. "30 Jun 2026")
  status?: AtrActionStatus;
  /** What the risk owner actually did to remediate (shown before Evidence). */
  actionTaken?: string;
  /** Evidence / comments backing the action. */
  evidence?: string;
  /** Management comments or checker / auditor verification. */
  verification?: string;
  /** The auditor's decision on the plan itself, before the work begins.
   *  Absent = not yet submitted for approval. */
  planReview?: AtrPlanReview;
  /** How far the risk owner's approval flow has got on this plan — the index of
   *  the level now deciding. Only meaningful while `planReview` is Pending. */
  approvalLevel?: number;
  /** The same, for the later review of the action actually taken. */
  actionLevel?: number;
  planReviewComment?: string;
  /** The case-management case this plan tracks, when it was created or updated
   *  from Manage Exceptions (see atrTimeline.ts). */
  caseId?: string;
  /** Raised through the report's own close-out journey (atrCloseout.ts). That
   *  journey starts empty on every page load, so the panel shows only the plans
   *  it raised itself — never the ones the report was generated with. */
  closeout?: true;
  /** The escalation matrix chasing THIS plan, when it needs one of its own —
   *  a plan owned by a different department to the rest of the observation.
   *  Absent means the observation's matrix governs it. See
   *  data/escalationMatrixStore.ts. */
  escalationMatrixId?: string;
}

/** Everything the report's own close-out journey records about an observation.
 *  It lives in its own object, apart from the fields the report was generated
 *  with, so the journey can never inherit them: it always starts at "the auditor
 *  assigns a risk owner". Session-only — see atrTimeline.dropCloseoutEvents. */
export interface AtrCloseout {
  /** Who remediates, and who verifies. */
  owner?: string;
  auditor?: string;
  /** True Exception (needs a sub-class + action plans) or False Positive
   *  (needs a reason, and closes with no plans). */
  verdict?: AtrVerdict;
  classification?: AtrClassification;
  classificationComment?: string;
  falsePositiveReason?: string;
  /** A False Positive is a claim that there is nothing to fix, so the auditor
   *  signs it off before it closes anything. Absent until the risk owner makes
   *  the call; 'Rejected' hands it back to be reclassified. */
  fpReview?: AtrPlanReview;
  fpReviewComment?: string;
  /** How far the approval flow has got on the false-positive call. */
  fpLevel?: number;
  /** The escalation matrix governing every action plan on this observation,
   *  unless a plan names its own. Tied by the auditor, chosen from the matrices
   *  configured in Administration → Escalation Matrix. */
  escalationMatrixId?: string;
}

/** A file or data source linked to an observation as supporting annexure. */
export interface AtrLinkedAnnexure {
  id: string;
  name: string;
  sizeBytes?: number;
  /** Where it came from in the Add-data picker. */
  source: 'upload' | 'source' | 'connect-db';
  linkedAt: string;   // ISO
  linkedBy: string;
}

export interface AtrObservation {
  title: string;
  /** Annexures linked to this observation from the saved report (the link icon
   *  on each observation card). */
  linkedAnnexures?: AtrLinkedAnnexure[];
  /** For ATRs generated by Create Report: the id of the extracted
   *  observation this came from, so the saved report can reach back to the
   *  wizard session's linked annexures (the per-observation Manage Exceptions
   *  CTA). Absent on hand-authored / curated ATRs. */
  sourceObservationId?: string;
  /** Audited process / area — drives the Process-Wise Summary when present. */
  process?: string;
  /** Observation / issue description. */
  description?: string;
  /** Optional one-line query summary. */
  querySummary?: string;
  /** Audit root-cause category (see ROOT_CAUSE_OPTIONS). */
  rootCause?: string;
  /** Solution type — Incident / Systemic / Not applicable. */
  solutionType?: string;
  /** Risk implication category (Financial / Operational / …). */
  riskImplications?: string;
  /** Free-text elaboration of the risk implications. */
  riskImplicationsDetails?: string;
  classification?: AtrClassification;
  risk?: AtrRisk;
  status?: AtrObservationStatus;
  /** The report's own close-out journey — assign, classify, plan, act, verify.
   *  Namespaced so it never reads the report's generated content as progress. */
  closeout?: AtrCloseout;
  /** Number of underlying flagged exceptions that roll up into this observation. */
  exceptions?: number;
  actionPlans: AtrActionPlan[];
}

export interface AtrInsight {
  title: string;
  body: string;
}

export interface AtrMeta {
  reportId: string;
  /** Human report name shown in the header (in place of the raw Report ID). */
  reportName?: string;
  /** Report Number — unique per Section within a Financial Year. */
  reportNumber?: string;
  /** Financial year the report covers, e.g. "FY 2025-26". */
  financialYear?: string;
  /** Audit vs Assurance section (governs Report-Number uniqueness namespace). */
  section?: string;
  /** Review type — Depth / IAR / FSR / FCR. */
  reviewType?: string;
  /** Audit location — Corporate / Circle / Corporate & Circle. */
  auditLocation?: string;
  /** Region / city — from the report details. */
  region?: string;
  location?: string;
  /** Business function the audit belongs to. */
  auditFunction?: string;
  /** The signed-in user who created the ATR. */
  auditSpoc?: string;
  auditTitle?: string;
  auditPeriod?: string;
  preparedBy?: string;
  reviewedBy?: string;
  generatedOn?: string;
  auditEntity?: string;
  /** Admin-added custom report-details fields — values by key, and the labels
   *  they were shown under (so the ATR prints them without the admin store). */
  custom?: Record<string, string>;
  customLabels?: Record<string, string>;
  /** Optional override for the Total Exceptions KPI (else summed from observations). */
  totalExceptions?: number;
  /** Customize: brand accent (hex) applied to the cover banner. */
  brandColor?: string;
  /** Customize: company logo (data URL) shown on the cover/header. */
  logoDataUrl?: string;
  /** Section keys removed from this report during editing (AtrSectionKey[]). */
  hiddenSections?: string[];
}

/** Everything needed to re-render a generated ATR as a saved report. Stored on
 *  a GeneratedReport (`atrData`) when the user clicks "Add to Report". */
export interface AtrReportData {
  meta: AtrMeta;
  observations: AtrObservation[];
  insights: AtrInsight[];
}
