// Real export composers for the report download modal — PDF, Word, PPT.
//
// Follows the ATR exporter precedent (atrTemplate.ts): Word and PPT are
// Office-HTML blobs (.doc / .ppt — the HTML-in-Office trick Word and
// PowerPoint both import), PDF is a composed print window so the user saves
// via the browser's "Save as PDF". No Excel export by design (PRD ruling).

import * as XLSX from 'xlsx';
import type { DownloadPreviewSection } from './ReportDownloadModal';
import type { WorkflowResult } from './reportShared';

export type ReportExportContext = {
  reportName: string;
  reportTag?: string;
  reportId?: string;
  templateName?: string;
  generatedBy: string;
  generatedAt: string;
  sections: DownloadPreviewSection[];
};

const esc = (s?: string) =>
  (s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Strip the markdown the rich query answers carry — exports want plain prose.
const plain = (s?: string) =>
  (s ?? '')
    .replace(/```[\s\S]*?```/g, '')
    .replace(/[#>*_`]/g, '')
    .replace(/\[(.*?)\]\(.*?\)/g, '$1')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

const INK = '#0F0720';
const MUTED = '#6B5D82';
const BRAND = '#6A12CD';
const BRAND_DARK = '#550FA5';   // brand-700 — number-chip text
const BRAND_WASH = '#F7F0FF';   // brand-50 — number chips, table heads
const HAIRLINE = '#E5E7EB';     // canvas-border
// Purple banner palette — matches the on-screen CoverBanner gradient.
const BANNER_FROM = '#3B0B72';
const BANNER_TO = '#6A12CD';
const BANNER_EYEBROW = '#D8C2F2';  // AUDIT INTELLIGENCE eyebrow on purple
const BANNER_BYLINE = '#E3D3F7';   // byline on purple
// Inter-led sans for document + section titles — mirrors the on-screen report
// pages (now all Inter). Segoe UI / Calibri / Arial are the safe Office fallbacks.
const TITLE_FONT = "Inter,'Segoe UI',Calibri,Arial,sans-serif";

const sevColor = (sev: string) =>
  sev === 'High' ? '#B42318' : sev === 'Medium' ? '#B54708' : '#067647';

// ─── ATR-document building blocks (mirrors AtrDocument.tsx proportions) ───

// Purple gradient letterhead — mirrors the on-screen report cover / ATR banner:
// IRAME.AI lockup, white title, light byline over a brand gradient. A
// solid bgcolor backs the CSS gradient so Word (which ignores gradients) still
// fills purple; PDF/HTML render the gradient.
function brandBanner(ctx: ReportExportContext): string {
  const byline = [ctx.reportTag, `Generated by ${ctx.generatedBy}`, ctx.generatedAt].filter(Boolean).map(esc).join(' · ');
  return `<table width="100%" cellpadding="0" cellspacing="0">
    <tr><td bgcolor="${BRAND_DARK}" style="background:${BRAND_DARK};background:linear-gradient(135deg, ${BANNER_FROM}, ${BANNER_TO});padding:30px 36px;">
      <p style="margin:0 0 14px;line-height:1.25;">
        <span style="color:#FFFFFF;font-weight:bold;font-size:11pt;letter-spacing:1px;">IRAME.AI</span><br/>
        <span style="color:${BANNER_EYEBROW};font-size:6.5pt;font-weight:bold;letter-spacing:3px;">AUDIT INTELLIGENCE</span>
      </p>
      <h1 style="font-family:${TITLE_FONT};color:#FFFFFF;font-size:23pt;font-weight:bold;margin:0;line-height:1.15;">${esc(ctx.reportName)}</h1>
      ${byline ? `<p style="color:${BANNER_BYLINE};font-size:10pt;margin:7px 0 0;">${byline}</p>` : ''}
    </td></tr>
  </table>`;
}

// Metadata grid — 3-up label/value cells with the brand left-accent bar.
function metaCell(label: string, value?: string): string {
  if (!value) return '<td></td>';
  return `<td width="33%" style="padding:14px 18px 14px 0;vertical-align:top;">
    <div style="font-size:7.5pt;font-weight:bold;letter-spacing:1.5px;color:${MUTED};text-transform:uppercase;margin-bottom:5px;">${esc(label)}</div>
    <div style="border-left:3px solid ${BRAND};padding-left:10px;font-size:10pt;font-weight:bold;color:${INK};">${esc(value)}</div>
  </td>`;
}

function metaGrid(ctx: ReportExportContext): string {
  const queries = ctx.sections.filter(s => s.kind === 'query').length;
  const workflows = ctx.sections.filter(s => s.kind === 'workflow').length;
  const scope = workflows > 0
    ? `${workflows} ${workflows === 1 ? 'workflow' : 'workflows'}`
    : queries > 0 ? `${queries} ${queries === 1 ? 'query' : 'queries'}` : undefined;
  return `<table width="100%" cellpadding="0" cellspacing="0" style="border-bottom:1px solid ${HAIRLINE};margin:0 0 8px;">
    <tr>${metaCell('Report ID', ctx.reportId)}${metaCell('Report Type', ctx.reportTag)}${metaCell('Scope', scope)}</tr>
    <tr>${metaCell('Prepared By', ctx.generatedBy)}${metaCell('Generated On', ctx.generatedAt)}${metaCell('Template', ctx.templateName)}</tr>
  </table>`;
}

// Numbered section heading — brand-washed number chip + bold title.
function numberedHeading(n: number, title: string, sub?: string): string {
  return `<p style="margin:22px 0 ${sub ? '2px' : '10px'};">
    <span style="background:${BRAND_WASH};color:${BRAND_DARK};font-weight:bold;font-size:10pt;padding:3px 9px;">${n}</span>
    <span style="font-family:${TITLE_FONT};font-size:13.5pt;font-weight:bold;color:${INK};">&nbsp; ${esc(title)}</span>
  </p>${sub ? `<p style="margin:0 0 10px;color:${MUTED};font-size:9pt;">${esc(sub)}</p>` : ''}`;
}

// KPI tile grid — bordered tiles with the tone-coloured left accent, 4 per row.
function kpiTileGrid(stats: { label: string; value: string; accent?: string }[]): string {
  if (stats.length === 0) return '';
  const rows: string[] = [];
  for (let i = 0; i < stats.length; i += 4) {
    const cells = stats.slice(i, i + 4).map(st => `
      <td width="25%" style="border:1px solid ${HAIRLINE};border-left:3px solid ${st.accent ?? BRAND};padding:10px 14px;vertical-align:top;">
        <div style="font-size:15pt;font-weight:bold;color:${st.accent ?? BRAND};">${esc(st.value)}</div>
        <div style="font-size:7.5pt;font-weight:bold;color:${MUTED};text-transform:uppercase;letter-spacing:0.5px;margin-top:3px;">${esc(st.label)}</div>
      </td>`).join('');
    rows.push(`<tr>${cells}</tr>`);
  }
  return `<table width="100%" cellpadding="0" cellspacing="6" style="margin:0 0 8px;">${rows.join('')}</table>`;
}

// ─── Shared document body (Word + PDF) ───
function composeDocumentBody(ctx: ReportExportContext): string {
  let n = 0;
  return ctx.sections.map(s => {
    if (s.kind === 'cover') return '';
    n += 1;
    if (s.kind === 'summary') {
      return `${numberedHeading(n, s.title, 'Overall rollup from this report’s queries')}
        ${kpiTileGrid(s.stats ?? [])}
        <p style="margin:6px 0 8px;line-height:1.55;">${esc(s.content)}</p>`;
    }
    if (s.kind === 'stats') {
      return kpiTileGrid(s.stats ?? []);
    }
    if (s.kind === 'query') {
      const kpis = (s.kpis ?? []).map(k => `<b>${esc(k.label)}:</b> ${esc(k.value)}`).join(' &nbsp;·&nbsp; ');
      const findings = s.findings.map(f => `<li style="margin:0 0 3px;">${esc(f)}</li>`).join('');
      const observations = s.observations.map(o => `<li style="margin:0 0 3px;">${esc(o)}</li>`).join('');
      return `${numberedHeading(n, `${s.queryId} — ${s.queryTitle}`)}
        <p style="margin:0 0 6px;color:${MUTED};font-size:10pt;">${esc(s.risk)} · <span style="color:${sevColor(s.severity)};font-weight:bold;">${esc(s.severity)} severity</span></p>
        ${kpis ? `<p style="margin:0 0 6px;font-size:10pt;">${kpis}</p>` : ''}
        <p style="margin:0 0 6px;line-height:1.55;">${esc(plain(s.summary))}</p>
        ${findings ? `<p style="margin:8px 0 2px;"><b>Key findings</b></p><ul style="margin:0 0 6px;">${findings}</ul>` : ''}
        ${observations ? `<p style="margin:8px 0 2px;"><b>Observations</b></p><ul style="margin:0 0 6px;">${observations}</ul>` : ''}`;
    }
    if (s.kind === 'workflow') {
      const findings = s.findings.map(f => `<li style="margin:0 0 3px;">${esc(f)}</li>`).join('');
      return `${numberedHeading(n, `${s.workflowId} — ${s.workflowName}`)}
        <p style="margin:0 0 6px;color:${MUTED};font-size:10pt;"><span style="color:${sevColor(s.severity)};font-weight:bold;">${esc(s.severity)} severity</span></p>
        <p style="margin:0 0 6px;line-height:1.55;">${esc(plain(s.summary))}</p>
        ${findings ? `<ul style="margin:0 0 6px;">${findings}</ul>` : ''}`;
    }
    if (s.kind === 'note') {
      return `${numberedHeading(n, s.title)}<p style="margin:0 0 6px;line-height:1.5;">${esc(s.content)}</p>`;
    }
    if (s.kind === 'observation') {
      return `${numberedHeading(n, `${s.obsId} — ${s.title}`)}<p style="margin:0 0 6px;line-height:1.5;">${esc(s.description)}</p>`;
    }
    return '';
  }).join('');
}

function documentHtml(ctx: ReportExportContext): string {
  return `<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>${esc(ctx.reportName)}</title></head>
  <body style="font-family:Calibri,Arial,sans-serif;color:${INK};margin:0;">
    ${brandBanner(ctx)}
    ${metaGrid(ctx)}
    ${composeDocumentBody(ctx)}
    <hr style="border:none;border-top:1px solid ${HAIRLINE};margin:18px 0 8px;"/>
    <p style="color:${MUTED};font-size:9pt;">Generated by Auditify Copilot</p>
  </body></html>`;
}

// ─── Word (.doc) ───
export function exportReportWord(ctx: ReportExportContext) {
  triggerDownload(
    new Blob(['﻿', documentHtml(ctx)], { type: 'application/msword' }),
    `${ctx.reportName}.doc`,
  );
}

// ─── HTML (.html) — the composed document as a standalone web page ───
export function exportReportHtml(ctx: ReportExportContext) {
  triggerDownload(
    new Blob([documentHtml(ctx)], { type: 'text/html;charset=utf-8' }),
    `${ctx.reportName}.html`,
  );
}

// ─── PPT (.ppt) — title slide + one slide per section (PRD: exec summary + slide per query group) ───
// Slides keep the standard 16:9 deck ratio (960×540).
function slideShell(inner: string, background?: string): string {
  return `<div style="page-break-after:always;width:960px;height:540px;box-sizing:border-box;padding:48px 56px;font-family:Calibri,Arial,sans-serif;color:${INK};background:${background ?? '#FFFFFF'};border-bottom:1px solid #eee;">${inner}</div>`;
}

export function exportReportPpt(ctx: ReportExportContext) {
  const slides: string[] = [];
  // Title slide — purple gradient letterhead, matching the on-screen report
  // cover: white IRAME.AI lockup, light eyebrow, white title, light byline.
  slides.push(slideShell(`
    <p style="margin:0 0 100px;line-height:1.3;">
      <span style="color:#FFFFFF;font-weight:bold;font-size:14pt;letter-spacing:1.5px;">IRAME.AI</span><br/>
      <span style="color:${BANNER_EYEBROW};font-size:8pt;font-weight:bold;letter-spacing:4px;">AUDIT INTELLIGENCE</span>
    </p>
    <h1 style="font-family:${TITLE_FONT};font-weight:bold;font-size:32pt;margin:0 0 14px;color:#FFFFFF;">${esc(ctx.reportName)}</h1>
    <p style="font-size:13pt;color:${BANNER_BYLINE};margin:0;">${[ctx.reportTag, `Generated by ${ctx.generatedBy}`, ctx.generatedAt].filter(Boolean).map(esc).join(' · ')}</p>`, BRAND_DARK));

  for (const s of ctx.sections) {
    if (s.kind === 'summary') {
      const tiles = (s.stats ?? []).slice(0, 4).map(st =>
        `<td style="padding:12px 20px;border:1px solid ${HAIRLINE};border-left:3px solid ${st.accent ?? BRAND};"><div style="font-size:18pt;font-weight:bold;color:${st.accent ?? BRAND};">${esc(st.value)}</div><div style="font-size:8pt;color:${MUTED};text-transform:uppercase;letter-spacing:0.5px;">${esc(st.label)}</div></td>`).join('');
      slides.push(slideShell(`
        <h2 style="font-family:${TITLE_FONT};font-weight:bold;font-size:22pt;color:${INK};margin:0 0 16px;">${esc(s.title)}</h2>
        ${tiles ? `<table style="border-collapse:separate;border-spacing:8px 0;margin:0 0 18px -8px;"><tr>${tiles}</tr></table>` : ''}
        <p style="font-size:14pt;line-height:1.6;">${esc(s.content)}</p>`));
    } else if (s.kind === 'query') {
      const bullets = s.findings.slice(0, 4).map(f => `<li style="margin:0 0 8px;">${esc(f)}</li>`).join('');
      const kpis = (s.kpis ?? []).slice(0, 4).map(k =>
        `<td style="padding:10px 18px;border:1px solid ${HAIRLINE};border-left:3px solid ${BRAND};"><div style="font-size:16pt;font-weight:bold;color:${BRAND};">${esc(k.value)}</div><div style="font-size:9pt;color:${MUTED};">${esc(k.label)}</div></td>`).join('');
      slides.push(slideShell(`
        <p style="font-size:10pt;color:${MUTED};margin:0 0 4px;">${esc(s.queryId)} · ${esc(s.risk)} · <span style="color:${sevColor(s.severity)};font-weight:bold;">${esc(s.severity)}</span></p>
        <h2 style="font-family:${TITLE_FONT};font-weight:bold;font-size:18pt;color:${INK};margin:0 0 14px;">${esc(s.queryTitle)}</h2>
        ${kpis ? `<table style="border-collapse:collapse;margin:0 0 16px;"><tr>${kpis}</tr></table>` : ''}
        ${bullets ? `<ul style="font-size:12.5pt;line-height:1.5;margin:0;">${bullets}</ul>` : `<p style="font-size:12.5pt;">${esc(plain(s.summary))}</p>`}`));
    } else if (s.kind === 'workflow') {
      const bullets = s.findings.slice(0, 4).map(f => `<li style="margin:0 0 8px;">${esc(f)}</li>`).join('');
      slides.push(slideShell(`
        <p style="font-size:10pt;color:${MUTED};margin:0 0 4px;">${esc(s.workflowId)} · <span style="color:${sevColor(s.severity)};font-weight:bold;">${esc(s.severity)}</span></p>
        <h2 style="font-family:${TITLE_FONT};font-weight:bold;font-size:18pt;color:${INK};margin:0 0 14px;">${esc(s.workflowName)}</h2>
        ${bullets ? `<ul style="font-size:12.5pt;line-height:1.5;margin:0;">${bullets}</ul>` : `<p style="font-size:12.5pt;">${esc(plain(s.summary))}</p>`}`));
    } else if (s.kind === 'observation') {
      slides.push(slideShell(`
        <p style="font-size:10pt;color:${MUTED};margin:0 0 4px;">${esc(s.obsId)}</p>
        <h2 style="font-family:${TITLE_FONT};font-weight:bold;font-size:18pt;color:${INK};margin:0 0 14px;">${esc(s.title)}</h2>
        <p style="font-size:12.5pt;line-height:1.6;">${esc(s.description)}</p>`));
    }
  }

  const html = `<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:p="urn:schemas-microsoft-com:office:powerpoint" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>${esc(ctx.reportName)}</title></head><body style="margin:0;">${slides.join('')}</body></html>`;
  triggerDownload(
    new Blob(['﻿', html], { type: 'application/vnd.ms-powerpoint' }),
    `${ctx.reportName}.ppt`,
  );
}

// ─── Excel (.xlsx) — bulk-audit workbook, same pattern as the ATR exporter ───
// Sheet 1 summarises every workflow run; each workflow with flagged records
// gets its own sheet carrying the full output table.
export function exportBulkAuditExcel(reportName: string, workflows: WorkflowResult[]) {
  const wb = XLSX.utils.book_new();

  const summaryRows = workflows.map(w => ({
    'Workflow ID': w.workflowId,
    'Workflow Name': w.name,
    'Business Process': w.businessProcess ?? '',
    'Severity': w.severity,
    'Records Flagged': w.outputTable?.rows.length ?? 0,
    'Run Status': w.runStatus === 'failed' ? `failed (${w.failureReason ?? 'errored'})` : 'completed',
    'Findings': w.findings.length,
  }));
  const summaryWs = XLSX.utils.json_to_sheet(summaryRows);
  summaryWs['!cols'] = Object.keys(summaryRows[0] ?? { a: 1 }).map(() => ({ wch: 26 }));
  XLSX.utils.book_append_sheet(wb, summaryWs, 'Workflows');

  workflows.forEach(w => {
    if (!w.outputTable || w.outputTable.rows.length === 0) return;
    const ws = XLSX.utils.aoa_to_sheet([w.outputTable.columns, ...w.outputTable.rows]);
    ws['!cols'] = w.outputTable.columns.map(() => ({ wch: 24 }));
    // Sheet names cap at 31 chars and reject \ / ? * [ ] :
    XLSX.utils.book_append_sheet(wb, ws, w.workflowId.replace(/[\\/?*[\]:]/g, '-').slice(0, 31));
  });

  XLSX.writeFile(wb, `${reportName}.xlsx`);
}

// ─── PDF — composed print window; user picks "Save as PDF" ───
export function exportReportPdf(ctx: ReportExportContext): boolean {
  const w = window.open('', '_blank', 'width=900,height=1100');
  if (!w) return false; // popup blocked — caller surfaces the message
  w.document.write(`${documentHtml(ctx)}
    <script>window.onload = function () { window.focus(); window.print(); };</script>`);
  w.document.close();
  return true;
}
