import { Fragment, useState, type CSSProperties } from 'react';
import { List, FileText, ArrowLeft, Sparkles, Pencil, Layers, BarChart3, Table2, Gauge } from 'lucide-react';
import { ReportBrandBanner, ReportNumberedHeading } from './ReportDocumentChrome';
import { reportGradient, reportAccent, templateKind, sectionBlurb, sectionSummary } from './reportShared';
import { atrSubtitleFor, atrDescriptionFor } from './atrSections';
import { REPORT_TEMPLATES } from '../../data/mockData';

const sectionDomId = (name: string, i: number) => `tpl-preview-sec-${i}-${name.replace(/\W+/g, '-').toLowerCase()}`;

type PreviewTemplate = typeof REPORT_TEMPLATES[number] & {
  brand?: string;
  theme?: string;
  headerText?: string;
  /** Sheet footer line. The reader only renders a footer when the report carries
   *  one, so the preview must read it rather than invent a "Generated by" line. */
  footerText?: string;
};

type PreviewSection = {
  name: string;
  kind?: 'text' | 'kpi' | 'chart' | 'table';
  metric?: string;
  chartType?: 'bar' | 'line';
  description?: string;
};

/** Body placeholder — the shape of the content a section will hold once the
 *  report is generated. Read-only; nothing here is wired to data. */
function SectionBody({ section }: { section: PreviewSection }) {
  const kind = section.kind ?? 'text';
  const metric = section.metric?.trim();

  if (kind === 'kpi') {
    return (
      <div className="flex items-center gap-4">
        <div className="shrink-0">
          <div className="text-[1.75rem] font-bold text-ink-300 leading-none tabular-nums">—</div>
          <div className="text-[0.75rem] font-semibold uppercase tracking-wider text-ink-400 mt-1.5">{metric || 'Metric'}</div>
        </div>
        <p className="text-[0.75rem] text-ink-400 leading-relaxed">KPI filled from query data at generation.</p>
      </div>
    );
  }
  if (kind === 'chart') {
    return (
      <div className="max-w-[75%]">
        <div className="flex items-end gap-1.5 h-14">
          {(section.chartType ?? 'bar') === 'bar'
            ? [40, 68, 30, 82, 54, 72].map((h, k) => <div key={k} className="flex-1 rounded-t-[3px] bg-canvas-border" style={{ height: `${h}%` }} />)
            : <svg viewBox="0 0 120 40" className="w-full h-full text-canvas-border" preserveAspectRatio="none"><polyline points="0,32 24,20 48,26 72,10 96,16 120,6" fill="none" stroke="currentColor" strokeWidth="2" /></svg>}
        </div>
        <p className="text-[0.75rem] font-semibold uppercase tracking-wider text-ink-400 mt-2">{metric || 'Metric'} · {section.chartType ?? 'bar'} chart</p>
      </div>
    );
  }
  if (kind === 'table') {
    return (
      <div className="max-w-[90%] rounded-[6px] overflow-hidden border border-canvas-border">
        <div className="grid grid-cols-4 bg-canvas">
          {Array.from({ length: 4 }).map((_, c) => <div key={c} className="h-4 border-r last:border-r-0 border-canvas-border" />)}
        </div>
        {Array.from({ length: 3 }).map((_, r) => (
          <div key={r} className="grid grid-cols-4 border-t border-canvas-border">
            {Array.from({ length: 4 }).map((_, c) => <div key={c} className="h-4 border-r last:border-r-0 border-canvas-border" />)}
          </div>
        ))}
      </div>
    );
  }
  // Text body. A section is where content goes, not where an instructional hint is
  // printed as body (PRD live-bug). So: a real author description shows as prose; a
  // query-driven section shows a query placeholder (the queries you add fill it);
  // anything else shows an add-description prompt. Never the generic blurb as body.
  const realDesc = section.description?.trim() && section.description.trim() !== sectionBlurb(section.name);
  if (realDesc) {
    return <p className="max-w-[80ch] text-[0.875rem] text-ink-700 leading-[1.8]">{section.description}</p>;
  }
  // A query section's body is empty here — the Query-results placeholder (rendered
  // right after it) shows where its cards land. A recognised heading shows its
  // one-line summary; anything else falls to the add-description prompt.
  const isQuerySection = /quer(y|ies)|testing results|findings/i.test(section.name);
  if (isQuerySection) return null;
  const summary = sectionSummary(section.name);
  if (summary) {
    return <p className="max-w-[80ch] text-[0.875rem] text-ink-700 leading-[1.8]">{summary}</p>;
  }
  return (
    <div className="max-w-[80ch] rounded-[10px] border border-dashed border-canvas-border bg-canvas/40 px-4 py-3 flex items-center gap-2 text-[0.8125rem] text-ink-500">
      <Pencil size={14} className="text-ink-400 shrink-0" /> This section has no description yet — add one and it appears here.
    </div>
  );
}

/** Where the report's query cards render — shown in the preview as an empty
 *  placeholder so the reader sees where the queries they add will land, and the
 *  shape of what a query brings (KPIs, a graph, a table). No real data: these fill
 *  from Ask IRA at generation. */
function QueryResultsPlaceholder() {
  return (
    <div className="scroll-mt-4 border-x border-canvas-border bg-white px-9 py-5">
      <div className="rounded-[12px] border border-dashed border-canvas-border bg-canvas/40 p-5">
        <div className="flex items-center gap-2">
          <Layers size={14} className="text-brand-600" />
          <span className="text-[0.6875rem] font-semibold uppercase tracking-[0.1em] text-ink-500">Query results</span>
          <span className="text-[0.75rem] text-ink-400">· fill from Ask IRA at generation</span>
        </div>
        <p className="text-[0.8125rem] text-ink-500 mt-1.5 mb-4">The queries you add to this report appear here — each with its KPIs, graph and table.</p>
        {/* KPI row */}
        <div className="mb-1 flex items-center gap-1.5 text-[0.625rem] font-semibold uppercase tracking-wide text-ink-400"><Gauge size={11} className="text-brand-600/70" /> KPIs</div>
        <div className="grid grid-cols-4 gap-2.5 mb-4">
          {[0, 1, 2, 3].map(i => (
            <div key={i} className="rounded-[8px] border border-canvas-border bg-white px-3 py-2.5">
              <div className="text-[1.25rem] font-bold text-ink-300 tabular-nums leading-none">—</div>
              <div className="mt-2 h-1.5 w-2/3 rounded-full bg-ink-900/[0.06]" />
            </div>
          ))}
        </div>
        {/* graph + table side by side */}
        <div className="grid grid-cols-2 gap-3">
          <div className="rounded-[8px] border border-canvas-border bg-white p-3">
            <div className="mb-2 flex items-center gap-1.5 text-[0.625rem] font-semibold uppercase tracking-wide text-ink-400"><BarChart3 size={11} className="text-brand-600/70" /> Graph</div>
            <div className="flex items-end gap-1 h-14">
              {[40, 68, 30, 82, 54, 72, 48].map((h, k) => <div key={k} className="flex-1 rounded-t-[2px] bg-canvas-border" style={{ height: `${h}%` }} />)}
            </div>
          </div>
          <div className="rounded-[8px] border border-canvas-border bg-white p-3">
            <div className="mb-2 flex items-center gap-1.5 text-[0.625rem] font-semibold uppercase tracking-wide text-ink-400"><Table2 size={11} className="text-brand-600/70" /> Table</div>
            <div className="rounded-[4px] overflow-hidden border border-canvas-border">
              <div className="grid grid-cols-4 bg-canvas">{[0, 1, 2, 3].map(c => <div key={c} className="h-3.5 border-r last:border-r-0 border-canvas-border" />)}</div>
              {[0, 1, 2].map(r => <div key={r} className="grid grid-cols-4 border-t border-canvas-border">{[0, 1, 2, 3].map(c => <div key={c} className="h-3.5 border-r last:border-r-0 border-canvas-border" />)}</div>)}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

/** The report a standard template produces, as a full page: the reader's own
 *  command bar, outline rail and sheet measurements, so the document renders at
 *  the width a real report renders at (~900px, not the 606px a modal allowed).
 *  Read-only, and every per-report value on the cover is a placeholder. */
export default function TemplatePreviewPage({ template, onClose, onGenerate, onDescriptionChange }: {
  template: PreviewTemplate;
  onClose: () => void;
  /** Start generating a report from this template (opens the Generate wizard). */
  onGenerate?: () => void;
  /** When set (custom templates only), the cover description is click-to-edit and
   *  saves back through this, mirroring the report reader's EditableDescription. */
  onDescriptionChange?: (desc: string) => void;
}) {
  const sections = (template.sections ?? []) as PreviewSection[];
  const theme = template.theme ?? 'Purple & White';
  const coverGradient = reportGradient(theme, '');
  const coverAccent = reportAccent(theme, '');

  // ATR is rendered by AtrDocument, not the generic reader: its cover titles
  // itself with the constant "Action Taken Report" (AtrDocument.tsx:273) and its
  // byline counts observations rather than queries, so its placeholders differ.
  const isAtr = templateKind(template) === 'atr';

  // Where the report renders its query cards: at a query / findings section, else
  // right after the Executive Summary (index 0). Shown as the Query-results
  // placeholder in the preview so the reader can see where the queries land. ATR
  // carries observation cards instead, so it gets no query placeholder.
  const queryAnchorIdx = isAtr ? -1 : sections.findIndex(s => /quer(y|ies)|testing results|findings/i.test(s.name));
  const queryAt = isAtr ? -1 : (queryAnchorIdx >= 0 ? queryAnchorIdx : (sections.length ? 0 : -1));

  // This is a template preview, so every per-report value on the cover is a
  // placeholder, never a real one. Showing today's date or a live period would
  // read as data this template does not have. Each slot names the field the
  // generated report fills, in the same position the reader puts it.
  const coverTitle = isAtr ? 'Action Taken Report' : template.name;
  const coverDesc = isAtr ? 'Entity · Financial year' : template.desc;
  const coverId = isAtr ? 'ATR-000000' : 'GR-000000';
  // First cell is the person who made the report (`generatedBy` / `preparedBy`),
  // so it names the field. "You" is a value that cell happens to hold when you
  // generate it yourself — on a shared or uploaded report it reads as someone's
  // name, so it is not a placeholder.
  const byline = isAtr
    ? ['Prepared by', 'Date', 'N observations']
    : ['Author', 'Date', 'N queries'];

  // Outline rail — mirrors the reader's "On this page". Read-only here: the
  // reader's rail reorders, renames and deletes; a standard template's outline
  // is fixed, so rows only scroll.
  const [activeSection, setActiveSection] = useState(0);
  const scrollTo = (i: number) => {
    setActiveSection(i);
    document.getElementById(sectionDomId(sections[i].name, i))?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  // Click-to-edit description — only when the caller allows it (custom templates,
  // non-ATR). Mirrors the report reader's EditableDescription: Save / Cancel with
  // ⌘↵ and Esc shortcuts.
  const canEditDesc = !!onDescriptionChange && !isAtr;
  const [editingDesc, setEditingDesc] = useState(false);
  const [descDraft, setDescDraft] = useState(coverDesc ?? '');
  const startEditDesc = () => { setDescDraft(coverDesc ?? ''); setEditingDesc(true); };
  const saveDesc = () => { onDescriptionChange?.(descDraft.trim()); setEditingDesc(false); };
  const cancelDesc = () => setEditingDesc(false);

  return (
    /* The reader's root is the scroll container (ReportView:2738). Without
       h-full + overflow-y-auto the page just clips at the viewport. */
    <div className="font-sans h-full overflow-y-auto bg-canvas" style={{ '--rep-accent': coverAccent } as CSSProperties}>
      {/* Same sticky command bar the reader uses (ReportView:2804). A preview has
          no report to act on, so it carries the Back affordance only. */}
      <div className="sticky top-0 z-30 bg-canvas px-6 lg:px-12 xl:px-[124px] h-16 flex items-center justify-between gap-4">
        <button
          onClick={onClose}
          className="inline-flex items-center gap-1.5 h-9 px-3 text-[0.75rem] font-semibold text-ink-600 bg-canvas-elevated border border-canvas-border rounded-[8px] hover:bg-canvas hover:text-ink-900 transition-colors cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-600/30"
        >
          <ArrowLeft size={14} /> Back to Templates
        </button>
        <div className="flex items-center gap-3">
          <span className="text-[0.75rem] font-semibold text-ink-400">Template preview</span>
          {onGenerate && (
            <button
              onClick={onGenerate}
              className="inline-flex items-center gap-1.5 h-9 px-3.5 text-[0.75rem] font-semibold text-white bg-brand-600 rounded-[8px] hover:bg-brand-500 transition-colors cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-600/30"
            >
              <Sparkles size={14} /> {isAtr ? 'Generate ATR' : 'Generate report'}
            </button>
          )}
        </div>
      </div>

      {/* Rail + sheet at the reader's own measurements, so the document renders
          at the width it renders at in a real report. */}
      <div className="px-6 lg:px-12 xl:px-[124px] pt-3 pb-8 flex items-start gap-8 xl:gap-10">
        {sections.length > 0 && (
          <aside className="hidden xl:block w-[252px] shrink-0 sticky top-[72px] self-start max-h-[calc(100vh-96px)] overflow-y-auto pr-1 -mr-1 rounded-[14px] border border-canvas-border bg-canvas-elevated p-3.5">
            <div className="flex items-center gap-2 mb-3 px-1">
              <List size={13} className="text-ink-400" />
              <span className="text-[0.75rem] font-semibold uppercase tracking-[0.13em] text-ink-400">On this page</span>
              <span className="ml-auto text-[0.75rem] font-semibold tabular-nums text-ink-400">{sections.length}</span>
            </div>
            <ol className="list-none p-0 m-0 space-y-0.5">
              {sections.map((section, i) => {
                const active = activeSection === i;
                return (
                  <li
                    key={section.name}
                    className={`relative flex items-center gap-1.5 py-2 pl-1 pr-1 rounded-[8px] transition-colors list-none ${active ? 'bg-brand-50' : 'hover:bg-brand-50/30'}`}
                  >
                    <span
                      className="shrink-0 w-5 text-[0.75rem] font-semibold font-mono tabular-nums text-right"
                      style={{ color: 'var(--rep-accent, #550fa5)', opacity: active ? 1 : 0.65 }}
                    >
                      {String(i + 1).padStart(2, '0')}
                    </span>
                    <button
                      onClick={() => scrollTo(i)}
                      aria-current={active ? 'true' : undefined}
                      className={`flex-1 min-w-0 text-left text-[0.875rem] truncate transition-colors cursor-pointer ${active ? 'font-semibold text-brand-700' : 'font-medium text-ink-600 hover:text-brand-700'}`}
                    >
                      {section.name}
                    </button>
                  </li>
                );
              })}
            </ol>
          </aside>
        )}

        {/* No max-width — the reader lets the sheet take the remaining column
            (ReportView:2822), which is what puts it at ~900px. Capping it here
            is what made the modal preview render the document at 606px. */}
        <div className="relative flex-1 min-w-0 rounded-[12px] shadow-[0_10px_34px_-14px_rgba(15,8,30,0.22)]">
          <ReportBrandBanner
            title={coverTitle}
            className="rounded-t-[12px]"
            gradient={coverGradient}
            eyebrow={<span className="font-mono text-[0.75rem] tracking-[0.04em] text-white/65">{coverId}</span>}
            actions={
              /* The reader shows Generate ATR here on every non-SOX report. It
                 acts on a report that exists, so the preview shows the slot
                 without an action behind it. */
              !isAtr && templateKind(template) !== 'sox' ? (
                <span
                  aria-hidden="true"
                  className="inline-flex items-center gap-1.5 h-9 px-3.5 text-[0.75rem] font-semibold text-white/70 bg-brand-700/60 border border-white/20 rounded-[8px]"
                >
                  <FileText size={14} /> Generate ATR
                </span>
              ) : undefined
            }
            footer={byline.length ? (
              /* Same strip the reader renders (ReportView:2995): first cell bold,
                 pipe dividers, the rest muted. */
              <div className="flex items-center gap-2.5 text-[0.875rem] flex-wrap">
                {byline.map((p, i) => (
                  <span key={i} className="inline-flex items-center gap-2.5">
                    {i > 0 && <span className="text-white/30" aria-hidden="true">|</span>}
                    <span className={i === 0 ? 'font-semibold text-white' : 'text-white/70'}>{p}</span>
                  </span>
                ))}
              </div>
            ) : undefined}
          >
            {editingDesc ? (
              <div>
                <textarea
                  value={descDraft}
                  onChange={e => setDescDraft(e.target.value)}
                  onKeyDown={e => {
                    if (e.key === 'Escape') { e.preventDefault(); cancelDesc(); }
                    else if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') { e.preventDefault(); saveDesc(); }
                  }}
                  rows={2}
                  autoFocus
                  placeholder="Add a description for this template…"
                  className="w-full max-w-[52ch] bg-white/95 border border-white/40 rounded-[8px] px-3 py-2 text-[0.875rem] text-ink-800 leading-snug placeholder:text-ink-400 focus:outline-none focus:ring-2 focus:ring-white/50 resize-none"
                />
                <div className="mt-2 flex items-center gap-2 text-[0.75rem]">
                  <button onClick={saveDesc} className="inline-flex items-center gap-1.5 h-8 px-3 rounded-[8px] bg-white text-brand-700 font-semibold hover:bg-white/90 transition-colors cursor-pointer">Save</button>
                  <button onClick={cancelDesc} className="h-8 px-3 rounded-[8px] text-white/70 hover:text-white font-semibold transition-colors cursor-pointer">Cancel</button>
                  <span className="ml-auto text-white/50">⌘↵ Save · Esc Cancel</span>
                </div>
              </div>
            ) : canEditDesc ? (
              <button
                onClick={startEditDesc}
                title="Click to edit this description"
                className="text-left text-[0.875rem] text-white/75 hover:text-white rounded-[6px] -mx-1 px-1 hover:bg-white/10 transition-colors cursor-text"
              >
                {coverDesc || 'Add a description for this template…'}
              </button>
            ) : coverDesc ? (
              <p className="text-[0.875rem] text-white/75">{coverDesc}</p>
            ) : null}
          </ReportBrandBanner>

          {sections.map((section, i) => {
            // Subtitles are static report copy, so the preview shows the real
            // ones: ATR's come from atrSections; the generic reader only puts a
            // strapline under Executive Summary (ReportView:3024).
            const subtitle = isAtr
              ? atrSubtitleFor(section.name)
              : /executive summary/i.test(section.name)
                ? 'Overall observation and action plan rollup'
                : undefined;
            // ATR sections describe what they do (atrSections), matching the
            // Internal Audit template. The real ATR fills them with run data
            // (KPI tiles, observation cards); this is the preview's plain-English
            // explanation of each section.
            const atrDesc = isAtr ? atrDescriptionFor(section.name) : undefined;
            return (
              <Fragment key={section.name}>
                <div id={sectionDomId(section.name, i)} className="scroll-mt-4 border-x border-canvas-border bg-white px-9 pt-6 pb-6">
                  <ReportNumberedHeading n={i + 1} title={section.name} subtitle={subtitle} />
                  {isAtr
                    ? (atrDesc ? <p className="max-w-[80ch] text-[0.875rem] text-ink-700 leading-[1.8]">{atrDesc}</p> : null)
                    : <SectionBody section={section} />}
                </div>
                {i === queryAt && <QueryResultsPlaceholder />}
              </Fragment>
            );
          })}

          {/* The reader renders a footer strip only when the report carries
              footerText; standard templates carry none, so it stays off. */}
          {template.footerText ? (
            <div className="rounded-b-[12px] border-x border-b border-canvas-border bg-white px-9 py-5">
              <p className="text-[0.75rem] text-ink-400 tracking-wide">{template.footerText}</p>
            </div>
          ) : (
            <div className="rounded-b-[12px] border-x border-b border-canvas-border bg-white h-3" />
          )}
        </div>
      </div>
    </div>
  );
}
