// Link between an ATR saved in the Reports module and the Create Report
// wizard session it was generated from.
import type { ExtractionSession } from './types';

/** Saved-report ids for ATRs generated by Create Report: the prefix plus
 *  the wizard session id, so the report can find its session again. */
export const UPLOAD_REPORT_ID_PREFIX = 'gr-atr-upload-';

/** The wizard session an uploaded-ATR report card was generated from, read from
 *  the wizard's persisted store. Null for any other report, or if the extracted
 *  report has since been deleted from Observations Extracted. */
export function loadUploadSession(reportId: string): ExtractionSession | null {
  if (!reportId.startsWith(UPLOAD_REPORT_ID_PREFIX)) return null;
  const sessionId = reportId.slice(UPLOAD_REPORT_ID_PREFIX.length);
  try {
    const raw = localStorage.getItem('irame.atr-upload.v1');
    if (!raw) return null;
    const parsed = JSON.parse(raw) as { sessions?: ExtractionSession[]; session?: ExtractionSession | null };
    const sessions = Array.isArray(parsed.sessions) ? parsed.sessions : parsed.session ? [parsed.session] : [];
    return sessions.find(s => s.id === sessionId) ?? null;
  } catch { return null; }
}
